[build]
  command = "npm run build"
  publish = "public"

[[plugins]]
  package = "@netlify/plugin-functions-install-core"

[functions]
  directory = "functions"

[dev]
  command = "node demo3.js"
  port = 3000
